-- CreateEnum
CREATE TYPE "ExerciseNames" AS ENUM ('INCLINE_BENCH_PRESS', 'INCLINE_DUMBBELL_PRESS', 'INCLINE_CABLE_FLY', 'BENCH_PRESS', 'DUMBBELL_PRESS', 'CABLE_CROSSOVER', 'DECLINE_BENCH_PRESS', 'DECLINE_DUMBBELL_PRESS', 'DECLINE_CABLE_FLY', 'PULL_UP', 'LAT_PULLDOWN', 'BARBELL_ROW', 'DUMBBELL_ROW', 'SEATED_CABLE_ROW', 'T_BAR_ROW', 'BACK_EXTENSION', 'MILITARY_PRESS', 'DUMBBELL_SHOULDER_PRESS', 'FRONT_RAISE', 'LATERAL_RAISE', 'CABLE_LATERAL_RAISE', 'REVERSE_FLY', 'BARBELL_BICEP_CURL', 'DUMBBELL_BICEP_CURL', 'HAMMER_CURL', 'PREACHER_CURL', 'CLOSE_GRIP_BENCH_PRESS', 'TRICEP_PUSHDOWN', 'OVERHEAD_TRICEP_EXTENSION', 'SKULL_CRUSHER', 'SQUAT', 'HACK_SQUAT', 'LEG_PRESS', 'LEG_EXTENSION', 'ROMANIAN_DEADLIFT', 'LEG_CURL', 'STANDING_CALF_RAISE', 'SEATED_CALF_RAISE', 'HIP_THRUST', 'GLUTE_BRIDGE', 'CABLE_KICKBACK');

-- CreateEnum
CREATE TYPE "SetType" AS ENUM ('WARMUP', 'REGULAR', 'SUPERSET');

-- CreateEnum
CREATE TYPE "WeightUnit" AS ENUM ('KG');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" TEXT NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Exercise" (
    "id" TEXT NOT NULL,
    "name" "ExerciseNames" NOT NULL,
    "sessionId" TEXT NOT NULL,

    CONSTRAINT "Exercise_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Set" (
    "id" TEXT NOT NULL,
    "type" "SetType" NOT NULL DEFAULT 'REGULAR',
    "reps" INTEGER NOT NULL,
    "weight" DOUBLE PRECISION NOT NULL,
    "weightUnit" "WeightUnit" NOT NULL DEFAULT 'KG',
    "exerciseId" TEXT NOT NULL,

    CONSTRAINT "Set_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Exercise" ADD CONSTRAINT "Exercise_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Set" ADD CONSTRAINT "Set_exerciseId_fkey" FOREIGN KEY ("exerciseId") REFERENCES "Exercise"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
